# Form implementation generated from reading ui file 'windows/file_creating.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(533, 269)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.path.setEnabled(False)
        self.path.setGeometry(QtCore.QRect(10, 10, 511, 51))
        self.path.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.path.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"padding-left: 5px;\n"
"color: black;")
        self.path.setObjectName("path")
        self.chose_path = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chose_path.setGeometry(QtCore.QRect(10, 70, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.chose_path.setFont(font)
        self.chose_path.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chose_path.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.chose_path.setObjectName("chose_path")
        self.file_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.file_name.setEnabled(True)
        self.file_name.setGeometry(QtCore.QRect(10, 140, 511, 51))
        self.file_name.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.file_name.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"padding-left: 5px;\n"
"color: black;")
        self.file_name.setObjectName("file_name")
        self.create_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_file.setGeometry(QtCore.QRect(10, 200, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.create_file.setFont(font)
        self.create_file.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_file.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.create_file.setObjectName("create_file")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Створити файл - TextEditor"))
        self.path.setPlaceholderText(_translate("MainWindow", "Виберіть нище директорію, де буде знаходитись ваш файл, та шлях буде тут"))
        self.chose_path.setText(_translate("MainWindow", "Вибрати директорію..."))
        self.file_name.setPlaceholderText(_translate("MainWindow", "Напишіть сюди назву файлу"))
        self.create_file.setText(_translate("MainWindow", "Створити файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
