# Form implementation generated from reading ui file 'windows/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(610, 694)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_editor = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_editor.setGeometry(QtCore.QRect(10, 10, 591, 381))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_editor.setFont(font)
        self.text_editor.setStyleSheet("background: white;\n"
"color: black;\n"
"border-radius: 20px;\n"
"padding-left: 5px;\n"
"padding-top: 5px;")
        self.text_editor.setObjectName("text_editor")
        self.save_changes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_changes.setGeometry(QtCore.QRect(10, 400, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_changes.setFont(font)
        self.save_changes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_changes.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.save_changes.setObjectName("save_changes")
        self.clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(310, 400, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear.setFont(font)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clear.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.clear.setObjectName("clear")
        self.path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.path.setEnabled(False)
        self.path.setGeometry(QtCore.QRect(10, 490, 591, 51))
        self.path.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.path.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"padding-left: 5px;\n"
"color: black;")
        self.path.setObjectName("path")
        self.chose_path = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chose_path.setGeometry(QtCore.QRect(10, 550, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.chose_path.setFont(font)
        self.chose_path.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chose_path.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.chose_path.setObjectName("chose_path")
        self.create_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_file.setGeometry(QtCore.QRect(10, 620, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.create_file.setFont(font)
        self.create_file.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_file.setStyleSheet("QPushButton {\n"
"    background: #737373;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #525252;\n"
"}")
        self.create_file.setObjectName("create_file")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TextEditor"))
        self.text_editor.setPlaceholderText(_translate("MainWindow", "Введіть сюди текст файлу"))
        self.save_changes.setText(_translate("MainWindow", "Зберігти зміни"))
        self.clear.setText(_translate("MainWindow", "Очистити"))
        self.path.setPlaceholderText(_translate("MainWindow", "Тут буде шлях до вашого файлу"))
        self.chose_path.setText(_translate("MainWindow", "Вибрати..."))
        self.create_file.setText(_translate("MainWindow", "Створити файл..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
